repositories:
- bd4everyone/MicrobiomeProject
- seandavi/curatedMetagenomicDataETL
- seandavi/curatedMetagenomicsNextflow
- seandavi/nextflow_telemetry
- shbrief/curatedMetagenomicDataODM
- shbrief/lefserBenchmarking
- waldronlab/BugSigDB
- waldronlab/BugSigDBEnrich
- waldronlab/BugSigDBExports
- waldronlab/BugSigDBStats
- waldronlab/BugSigDBcuration
- waldronlab/HMP16SData
- waldronlab/MicrobiomeBenchmarkDataLefse
- waldronlab/MicrobiomeBenchmarkDataPrep
- waldronlab/MicrobiomeWorkshop
- waldronlab/PublicMicrobiomeProject
- waldronlab/bugSigSimple
- waldronlab/bugphyzz
- waldronlab/bugphyzzAnalyses
- waldronlab/bugphyzzExports
- waldronlab/bugsigdbr
- waldronlab/cMDmetaanalysis
- waldronlab/curatedMetagenomicData
- waldronlab/curatedMetagenomicDataAnalyses
- waldronlab/curatedMetagenomicDataCuration
- waldronlab/curatedMetagenomicDataPipeline
- waldronlab/curatedMetagenomicDataTerminal
- waldronlab/lefser
- waldronlab/taxPPro
- waldronlab/taxPProValidation
output_dir: ./cmgd_summaries
